"""Emit the tokens_per_step sweep for depth19_quad into configs/qwen3/tps_sweep/.

Arms are derived from `depth19_quad.yaml` by rewriting one line, so they cannot drift from the base
or from each other. Seed replicates at the incumbent best give the noise floor this study has never
had -- differences below it are unreadable.

    uv run python -m franken.scripts.qwen3.gen_tps_sweep
"""

from __future__ import annotations

import os
import re

BASE = "configs/qwen3/depth19_quad.yaml"
OUT = "configs/qwen3/tps_sweep"
# 32x range around the incumbent 32,768. Steps = tokens_per_epoch / tokens_per_step, so this is a
# step-count sweep: 244k down to 7.6k.
VALUES = [32_768, 16_384, 65_536, 8_192, 131_072, 262_144]  # priority order, not numeric
REPLICATE_SEEDS = [43, 44]  # at VALUES[0]


def arm(base: str, tokens_per_step: int, seed: int | None = None) -> tuple[str, str]:
    name = f"tps{tokens_per_step}" + (f"_s{seed}" if seed else "")

    def one(pattern: str, repl: str, text: str) -> str:
        out, n = re.subn(pattern, repl, text, count=1, flags=re.M)
        assert n == 1, f"{pattern!r} did not match {BASE} exactly once"
        return out

    body = one(r"^    tokens_per_step: .*$", f"    tokens_per_step: {tokens_per_step:_}", base)
    body = one(r"^  run_name: .*$", f"  run_name: qwen3_d19_quad_{name}", body)
    if seed is not None:
        body = one(r"^  seed: .*$", f"  seed: {seed}", body)
    header = (
        f"# GENERATED by franken/scripts/qwen3/gen_tps_sweep.py -- edit the generator.\n"
        f"# depth19_quad with tokens_per_step {tokens_per_step:,}"
        + (f", seed {seed} (replicate, for the noise floor).\n" if seed else ".\n")
    )
    return name, header + body[body.index("# multi_domain") :]


def main() -> None:
    root = os.path.join(os.path.dirname(__file__), "..", "..", "..")
    base = open(os.path.join(root, BASE)).read()
    out = os.path.abspath(os.path.join(root, OUT))
    os.makedirs(out, exist_ok=True)
    order = []
    for tps in VALUES:
        seeds = [None, *REPLICATE_SEEDS] if tps == VALUES[0] else [None]
        for seed in seeds:
            name, body = arm(base, tps, seed)
            with open(os.path.join(out, f"{name}.yaml"), "w") as f:
                f.write(body)
            order.append(f"{OUT}/{name}.yaml")
    with open(os.path.join(out, "ORDER.txt"), "w") as f:
        f.write("\n".join(order) + "\n")
    print(f"{len(order)} configs -> {out}")


if __name__ == "__main__":
    main()
