"""Emit the depth x ops x token_budget sweep into configs/qwen3/sweep/.

Grid is 9 depths x {exact, quad} x 4 budgets = 72 configs, ~3 days at 8 ranks. ORDER.txt lists them
most-informative-first so a batch stopped early still answers the depth question.

`max_seqs` tracks `token_budget / SEQ_RATIO` rather than staying at 256: held constant, the seq cap
binds on 57% of batches at 32768 and 4% at 8192, so the budget axis would be measuring the cap.
At a fixed ratio every budget sits at 89-91% padding efficiency and ~21% cap-bound.

    uv run python -m franken.scripts.qwen3.gen_sweep
"""

from __future__ import annotations

import os

TEACHER_DEPTH = 28
DEPTHS = range(19, 10, -1)
BUDGETS = [16384, 8192, 32768, 4096]  # priority order, not numeric: 16384 is the reference
SEQ_RATIO = 64
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "..", "configs", "qwen3", "sweep")


def layer_map(depth: int) -> list[int]:
    """Middle-cut: keep the teacher's first and last blocks, drop the middle. Generalizes the
    hand-written depth-19 map, which this reproduces exactly at depth 19."""
    front = depth // 2
    back = depth - front
    return list(range(front)) + list(range(TEACHER_DEPTH - back, TEACHER_DEPTH))


def config_yaml(depth: int, ops: str, budget: int) -> str:
    quad = ops == "quad"
    return f"""# GENERATED by franken/scripts/qwen3/gen_sweep.py -- edit the generator.
# depth {depth} / {"quad_silu d32 + range penalty (every layer)" if quad else "exact SiLU, no penalty"} / token_budget {budget} per rank.
# Pairs with d{depth}_{"exact" if quad else "quad"}_tb{budget}.yaml (ops lever) and the other budgets at this depth.

model:
  backend: qwen3
  num_hidden_layers: {depth}

  softmax: exact
  softmax_kwargs: {{}}
  {"activation: quad_silu" if quad else "activation: silu # Qwen3's SwiGLU nonlinearity is SiLU, NOT GELU"}
  activation_kwargs: {"{ domain: 32 }" if quad else "{} # ExactSiLU takes no ctor args: `domain` would be a TypeError, not a no-op"}
  attn_impl: sdpa_causal

distill:
  beta: 1.0
  hidden_layer_map: {layer_map(depth)}
  range_penalty: {"1.0" if quad else "0.0 # exact SiLU has no bounded domain to squash into"}
  range_penalty_layers: null # every layer

train:
  teacher_model: Qwen/Qwen3-Embedding-0.6B
  teacher_ckpt: null
  task: embed
  corpus: multi_domain
  # v8 mix (pubmed -> arxiv) measures 110.3 tok/text: 2.01B token-passes over 2 epochs.
  corpus_size: 9100000
  output_dir: outputs
  run_name: qwen3_d{depth}_{ops}_tb{budget}
  max_seq_len: 1024
  seed: 42
  device: cuda
  precision: bf16
  compile: true

  teacher:
    lr: 5.0e-5
    epochs: 3
    batch_size: 32
    warmup_ratio: 0.1
    weight_decay: 0.01

  distill:
    # null, NOT hardcoded: the budget axis moves the global batch 8x, and one fixed lr would make
    # this a sweep of how undertrained the big-batch arms are.
    lr: null
    epochs: 2
    token_budget: {budget}
    max_seqs: {budget // SEQ_RATIO}
    warmup_ratio: 0.1
    weight_decay: 0.01
"""


def main() -> None:
    out = os.path.abspath(OUT)
    os.makedirs(out, exist_ok=True)
    order = []
    for budget in BUDGETS:
        for depth in DEPTHS:
            for ops in ("exact", "quad"):
                stem = f"d{depth}_{ops}_tb{budget}"
                with open(os.path.join(out, f"{stem}.yaml"), "w") as f:
                    f.write(config_yaml(depth, ops, budget))
                order.append(f"configs/qwen3/sweep/{stem}.yaml")
    with open(os.path.join(out, "ORDER.txt"), "w") as f:
        f.write("\n".join(order) + "\n")
    print(f"{len(order)} configs -> {out}")
    print(f"order: {os.path.join(out, 'ORDER.txt')}")


if __name__ == "__main__":
    main()
